### ISSUE TITLE
Drop Support for Python 3.9

### ISSUE THREAD

**Issue by jmgate** [sandialabs/reverse_argparse#16]
## Tasks
* [x] Update `pyproject.toml` to reflect the change.
* [x] Update the badge in `README.md`.
* [x] Update the CI file.
* [x] Use the match-case statement in `_unparse_args()`.
* [x] See if there are any other 3.10 features to use within the code.
