### ISSUE TITLE
Consider adding dynamic analysis tools

### ISSUE THREAD

**Issue by jmgate** [sandialabs/reverse_argparse#37]
## Description
From the OpenSSF Best Practices badge program:

![Screenshot 2023-07-25 at 12 24 11 PM](https://github.com/sandialabs/reverse_argparse/assets/20327215/53139be8-6519-405f-a8f6-630d88e27ce0)

Perhaps we should consider adding some [dynamic code analysis tools](https://github.com/analysis-tools-dev/dynamic-analysis#python) to our CI.

## Tasks
* [ ] Investigate potential tools.
* [ ] Determine which ones to adopt.
* [ ] Add each to CI.

**Comment by jmgate** [comment]
It may be that using the [Hypothesis](https://hypothesis.readthedocs.io/en/latest/) library in unit testing would be sufficient.

**Comment by jmgate** [comment]
Or perhaps [DynaPyt](https://github.com/sola-st/DynaPyt) is worth looking into.
